### PR TITLE
WIP: support plugin

### PR DESCRIPTION
**Pull request by justforlxz**

### CODE REVIEW

**Comment by justforlxz** [comment]
I plan to expand the functionality through plugin, such as expanding search and display flatpak, appimage.

For example, #88 will reduce code and make it much more convenient.

**Comment by rsanjuan87** [comment]
That's cool
Could you provide some doc to create a básico plugin using this API to perform the searches like in the PR you mentioned

**Comment by xmuli** [comment]
nice, so fast

**Comment by justforlxz** [comment]
As i said on twitter. how does the taskbar locked custom data? It only supports searchable desktop files. Sending to the desktop will also be affected. One of the solutions is that non-desktop file types are forbidden to be dragged and moved, because essentially this function serves desktop files.

**Comment by justforlxz** [comment]
> That's cool
> Could you provide some doc to create a basic plugin using this API to perform the searches like at the Pull Request you mentioned

I will. My team and I are planning to release detailed documentation on plug-in development and interfaces under dde, and we will improve the plug-in interface so that the community can expand freely.

**Comment by wentaosong1993** [comment]
> > That's cool
> > Could you provide some doc to create a basic plugin using this API to perform the searches like at the Pull Request you mentioned
> 
> I will. My team and I are planning to release detailed documentation on plug-in development and interfaces under dde, and we will improve the plug-in interface so that the community can expand freely.

@rsanjuan87 I agree with it.

**Pull request closed without merging**
